[2024-09-03T19:17:48.543+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl-cocktails.obtencion-operator manual__2024-09-03T19:16:44.374424+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
